name: build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew clean test build
      - uses: actions/upload-artifact@v4
        with:
          name: viGeyserUpdater
          path: |
            bukkit/build/libs/viGeyserUpdater-Bukkit-*.jar
            velocity/build/libs/viGeyserUpdater-Velocity-*.jar
